import { useEffect, useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { ThemeToggle } from './ThemeToggle';
import { listBriefings } from '../lib/data';

const linkClass = ({ isActive }: { isActive: boolean }) =>
  `relative py-1 transition-colors ${
    isActive
      ? 'text-stone-900 dark:text-stone-50 font-medium after:absolute after:left-0 after:right-0 after:-bottom-[1px] after:h-[2px] after:bg-accent-500'
      : 'text-stone-500 dark:text-stone-400 hover:text-stone-900 dark:hover:text-stone-100'
  }`;

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="sticky top-0 z-20 border-b border-stone-200/70 dark:border-stone-800/70 bg-paper/80 dark:bg-ink/80 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between gap-3">
          <Link to="/" className="group flex items-center gap-2 shrink-0">
            <span
              aria-hidden
              className="inline-block w-2 h-2 sm:w-2.5 sm:h-2.5 rounded-full bg-accent-500 group-hover:bg-accent-400 transition-colors"
            />
            <span className="font-serif text-[16px] sm:text-[18px] font-semibold tracking-tight text-stone-900 dark:text-stone-50">
              arxiv<span className="text-accent-500">·</span>radar
            </span>
          </Link>
          <nav className="flex items-center gap-3 sm:gap-6 text-[13px] sm:text-sm">
            <NavLink to="/" end className={linkClass}>Daily</NavLink>
            <NavLink to="/trends" className={linkClass}>Trends</NavLink>
            <NavLink to="/bookmarks" className={linkClass}>Bookmarks</NavLink>
            <NavLink to="/info" className={linkClass}>Info</NavLink>
            <span className="hidden sm:inline-block w-px h-4 bg-stone-300 dark:bg-stone-700" />
            <ThemeToggle />
          </nav>
        </div>
      </header>
      <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-10">{children}</main>
      <Footer />
    </div>
  );
}

function Footer() {
  const [latest, setLatest] = useState<string | null>(null);
  useEffect(() => {
    listBriefings()
      .then((files) => {
        if (files[0]) setLatest(files[0].replace('.json', ''));
      })
      .catch(() => { /* silent — footer is non-critical */ });
  }, []);

  return (
    <footer className="border-t border-stone-200/70 dark:border-stone-800/70 mt-16">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 text-[12px] text-stone-500 dark:text-stone-400 flex flex-wrap items-center justify-between gap-x-6 gap-y-2">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1">
          <a
            href="https://github.com/meelod/arxiv-trend-radar"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-stone-800 dark:hover:text-stone-200 transition-colors"
          >
            github.com/meelod/arxiv-trend-radar
          </a>
          {latest && (
            <>
              <span aria-hidden className="w-px h-3 bg-stone-300 dark:bg-stone-700" />
              <span>
                Last brief <span className="font-mono text-stone-600 dark:text-stone-300">{latest}</span>
              </span>
            </>
          )}
        </div>
        <span className="text-stone-400 dark:text-stone-500">
          Generated by AI &mdash; verify before acting on any specific claim.
        </span>
      </div>
    </footer>
  );
}

