import { Link, NavLink } from 'react-router-dom';
import { ThemeToggle } from './ThemeToggle';

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="font-semibold text-zinc-900 dark:text-zinc-100">
            arxiv-trend-radar
          </Link>
          <nav className="flex items-center gap-6 text-sm">
            <NavLink
              to="/"
              end
              className={({ isActive }) =>
                `transition-colors ${isActive ? 'text-accent-500 font-medium' : 'text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100'}`
              }
            >
              Daily
            </NavLink>
            <NavLink
              to="/trends"
              className={({ isActive }) =>
                `transition-colors ${isActive ? 'text-accent-500 font-medium' : 'text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100'}`
              }
            >
              Trends
            </NavLink>
            <NavLink
              to="/bookmarks"
              className={({ isActive }) =>
                `transition-colors ${isActive ? 'text-accent-500 font-medium' : 'text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100'}`
              }
            >
              Bookmarks
            </NavLink>
            <NavLink
              to="/info"
              className={({ isActive }) =>
                `transition-colors ${isActive ? 'text-accent-500 font-medium' : 'text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100'}`
              }
            >
              Info
            </NavLink>
            <ThemeToggle />
          </nav>
        </div>
      </header>
      <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-8">{children}</main>
      <footer className="border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 mt-12">
        <div className="max-w-5xl mx-auto px-6 py-4 text-xs text-zinc-500 dark:text-zinc-400">
          Generated by AI — verify before acting on any specific claim.
        </div>
      </footer>
    </div>
  );
}
